/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import BackendDB4OUtility.DB4;
import OperatingSystems.Operatesys;
import AdministrationInterface.AdminMainPage;
import OrganBankInterface.DonarBankLandingPage;
import HealthcareInterface.HospitalLandingPage;
import ClinicalInterface.MainLabCoverPage;
import SupplyChainInterface.LogisticsFrontPage;



import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;
import javax.swing.*;
import java.awt.*;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
/**
 *
 * @author asus
 */
public class MainJFrameForm extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrameForm
     */
    
    private Operatesys operatingSystem;
    private DB4 dB4OUtility = DB4.getInstance();
    
    ImageIcon myImage;

    public ImageIcon setIcon(String m) {
        if (m != null) {
            myImage = new ImageIcon(m);
        }
        Image img1 = myImage.getImage();
        Image img2 = img1.getScaledInstance(442, 266, Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        return i;

    }
    
    public MainJFrameForm() {
        initComponents();
        this.setSize(1200, 750);
        this.operatingSystem = dB4OUtility.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPageSplit = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        LogisPanel = new javax.swing.JPanel();
        Log_lbl = new javax.swing.JLabel();
        donorPanel = new javax.swing.JPanel();
        DonorBank_lbl = new javax.swing.JLabel();
        LabPanel = new javax.swing.JPanel();
        Lab_lbl = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        Admin_lbl = new javax.swing.JLabel();
        HospitalPanel = new javax.swing.JPanel();
        Hospital_lbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        OrganTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogisPanel.setBackground(new java.awt.Color(255, 255, 255));
        LogisPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogisPaneljPanel4MouseClicked(evt);
            }
        });

        Log_lbl.setBackground(new java.awt.Color(51, 51, 51));
        Log_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Log_lbl.setForeground(new java.awt.Color(204, 0, 51));
        Log_lbl.setText("Supply Chain");

        javax.swing.GroupLayout LogisPanelLayout = new javax.swing.GroupLayout(LogisPanel);
        LogisPanel.setLayout(LogisPanelLayout);
        LogisPanelLayout.setHorizontalGroup(
            LogisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(Log_lbl)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        LogisPanelLayout.setVerticalGroup(
            LogisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Log_lbl)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel10.add(LogisPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 370, 50));

        donorPanel.setBackground(new java.awt.Color(255, 255, 255));
        donorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donorPanelMouseClicked(evt);
            }
        });

        DonorBank_lbl.setBackground(new java.awt.Color(255, 255, 255));
        DonorBank_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DonorBank_lbl.setForeground(new java.awt.Color(204, 0, 0));
        DonorBank_lbl.setText("Organ Bank");

        javax.swing.GroupLayout donorPanelLayout = new javax.swing.GroupLayout(donorPanel);
        donorPanel.setLayout(donorPanelLayout);
        donorPanelLayout.setHorizontalGroup(
            donorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donorPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(DonorBank_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        donorPanelLayout.setVerticalGroup(
            donorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donorPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(DonorBank_lbl)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel10.add(donorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 370, -1));

        LabPanel.setBackground(new java.awt.Color(255, 255, 255));
        LabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabPanelMouseClicked(evt);
            }
        });

        Lab_lbl.setBackground(new java.awt.Color(51, 51, 51));
        Lab_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lab_lbl.setForeground(new java.awt.Color(204, 0, 0));
        Lab_lbl.setText("Clinical");

        javax.swing.GroupLayout LabPanelLayout = new javax.swing.GroupLayout(LabPanel);
        LabPanel.setLayout(LabPanelLayout);
        LabPanelLayout.setHorizontalGroup(
            LabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LabPanelLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(Lab_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        LabPanelLayout.setVerticalGroup(
            LabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Lab_lbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel10.add(LabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 370, 50));

        AdminPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminPanelMouseClicked(evt);
            }
        });

        Admin_lbl.setBackground(new java.awt.Color(51, 51, 51));
        Admin_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Admin_lbl.setForeground(new java.awt.Color(204, 0, 0));
        Admin_lbl.setText("Administration");

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(Admin_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Admin_lbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel10.add(AdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 370, 50));

        HospitalPanel.setBackground(new java.awt.Color(255, 255, 255));
        HospitalPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HospitalPanelMouseClicked(evt);
            }
        });

        Hospital_lbl.setBackground(new java.awt.Color(51, 51, 51));
        Hospital_lbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Hospital_lbl.setForeground(new java.awt.Color(204, 0, 0));
        Hospital_lbl.setText("Healthcare");

        javax.swing.GroupLayout HospitalPanelLayout = new javax.swing.GroupLayout(HospitalPanel);
        HospitalPanel.setLayout(HospitalPanelLayout);
        HospitalPanelLayout.setHorizontalGroup(
            HospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospitalPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(Hospital_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        HospitalPanelLayout.setVerticalGroup(
            HospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HospitalPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(Hospital_lbl)
                .addGap(14, 14, 14))
        );

        jPanel10.add(HospitalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 370, 50));

        MainPageSplit.setLeftComponent(jPanel10);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1620, 960));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrganTitle.setFont(new java.awt.Font("STSong", 1, 48)); // NOI18N
        OrganTitle.setForeground(new java.awt.Color(51, 51, 51));
        OrganTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrganTitle.setText("I-Care");
        jPanel3.add(OrganTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 220, 70));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/cross logo.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(960, 510));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 150, 1070, -1));

        MainPageSplit.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPageSplit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPageSplit)
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void sendMail() {

        try {
            Properties properties = new Properties();
//            properties.put("mail.smtp.auth", "true");
//            properties.put("mail.smtp.starttls.enable", "true");
//            properties.put("mail.smtp.host", "smtp.gmail.com");
//            properties.put("mail.smtp.port", "587");
            properties.put("mail.smtp.user", "username");
            
            properties.put("mail.smtp.host", "smtp.gmail.com");
            properties.put("mail.smtp.port", "25");
            properties.put("mail.debug", "true");
            properties.put("mail.smtp.auth", "true");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.EnableSSL.enable", "true");

            properties.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            properties.setProperty("mail.smtp.socketFactory.fallback", "false");
            properties.setProperty("mail.smtp.port", "465");
            properties.setProperty("mail.smtp.socketFactory.port", "465");
            String myAccountEmail = "sarthak2820@gmail.com";
          
            String password = "798564516565468798498jk";
            Session session;
            session = Session.getInstance(properties, new javax.mail.Authenticator() {
                @Override
                protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                    return new javax.mail.PasswordAuthentication(myAccountEmail, password);
                }
            });
            Message mailmsg = prepareMessage(session, myAccountEmail, "huntin@gmail.com", "msg", "sub");
            Transport.send(mailmsg);
// System.out.println("Successful sent");
        } catch (MessagingException ex) {
            ex.printStackTrace();
//            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private static Message prepareMessage(Session session, String myAccountEmail, String toAddress, String emailmsg, String emailsubject) {

        try {
            Message mailmsg = new MimeMessage(session);mailmsg.setFrom(new InternetAddress(myAccountEmail));mailmsg.setRecipient(Message.RecipientType.TO, new InternetAddress(toAddress));
            mailmsg.setSubject(emailsubject);mailmsg.setText(emailmsg);
            return mailmsg;
        } catch (MessagingException ex) {
            ex.printStackTrace();
              //JOptionPane.showMessageDialog(this,"Error sending mail");
//            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }
        return null;

    }
    
    private void LogisPaneljPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogisPaneljPanel4MouseClicked
        // TODO add your handling code here:
        //logistics
        LogisticsFrontPage LogisticsFrontPage = new LogisticsFrontPage(this, dB4OUtility, operatingSystem);
        MainPageSplit.setRightComponent(LogisticsFrontPage);
    }//GEN-LAST:event_LogisPaneljPanel4MouseClicked

    private void donorPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donorPanelMouseClicked
        // TODO add your handling code here:
        //Donor Bank
        DonarBankLandingPage DonorBankLandingPage = new DonarBankLandingPage(this, dB4OUtility, operatingSystem);
        MainPageSplit.setRightComponent(DonorBankLandingPage);
    }//GEN-LAST:event_donorPanelMouseClicked

    private void LabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabPanelMouseClicked
        // TODO add your handling code here:
        //Laboratory
        MainLabCoverPage MainLabCoverPage = new MainLabCoverPage(this, dB4OUtility, operatingSystem);
        MainPageSplit.setRightComponent(MainLabCoverPage);
    }//GEN-LAST:event_LabPanelMouseClicked

    private void AdminPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminPanelMouseClicked
        // TODO add your handling code here:
        //Admin
        AdminMainPage AdminPage = new AdminMainPage(this, dB4OUtility, operatingSystem);
        MainPageSplit.setRightComponent(AdminPage);
    }//GEN-LAST:event_AdminPanelMouseClicked

    private void HospitalPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HospitalPanelMouseClicked
        // TODO add your handling code here:
        //Hospital
        HospitalLandingPage HospitalLandingPage = new HospitalLandingPage(this, dB4OUtility, operatingSystem);
        MainPageSplit.setRightComponent(HospitalLandingPage);
    }//GEN-LAST:event_HospitalPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JLabel Admin_lbl;
    private javax.swing.JLabel DonorBank_lbl;
    private javax.swing.JPanel HospitalPanel;
    private javax.swing.JLabel Hospital_lbl;
    private javax.swing.JPanel LabPanel;
    private javax.swing.JLabel Lab_lbl;
    private javax.swing.JLabel Log_lbl;
    private javax.swing.JPanel LogisPanel;
    private javax.swing.JSplitPane MainPageSplit;
    private javax.swing.JLabel OrganTitle;
    private javax.swing.JPanel donorPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
