/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SupplyChainInterface;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import BackendDB4OUtility.DB4;
import OperatingSystems.Operatesys;
import BackendEnterpriseSupplyChain.Vehicle;

import model.MainJFrameForm;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author vidishaa
 */
public class VehicleSignUp extends javax.swing.JPanel {

    /**
     * Creates new form VehicleSignUp
     */
    boolean emptyValidationStatus = true;
    
    MainJFrameForm MainLPage;
    private Operatesys operatingSystem;
    private DB4 dB4OUtility;
    
    public VehicleSignUp(MainJFrameForm MainLPage, DB4 dB4OUtility, Operatesys operatingSystem) {
        initComponents();
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        admintitle = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        VehicleTxt = new javax.swing.JTextField();
        VehNumlbl = new javax.swing.JLabel();
        VehNumtxt = new javax.swing.JTextField();
        Address_lbl = new javax.swing.JLabel();
        TypeVehtxt = new javax.swing.JTextField();
        DescLbl = new javax.swing.JLabel();
        Desctxt = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        SignUpbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admintitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        admintitle.setText("Create Vehicle Profile");
        jPanel1.add(admintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        NameLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NameLbl.setText("Vehicle Name:");
        jPanel1.add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));
        jPanel1.add(VehicleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 177, -1));

        VehNumlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VehNumlbl.setText("Vehicle Number:");
        jPanel1.add(VehNumlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));
        jPanel1.add(VehNumtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 177, -1));

        Address_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Address_lbl.setText("Vehicle Type:");
        jPanel1.add(Address_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));
        jPanel1.add(TypeVehtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 177, -1));

        DescLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DescLbl.setText("Description:");
        jPanel1.add(DescLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));
        jPanel1.add(Desctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 177, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 87, 40));

        SignUpbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SignUpbtn.setText("Sign Up");
        SignUpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpbtnActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 87, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/delivery.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1412, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed

        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SignUpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpbtnActionPerformed
        // TODO add your handling code here:
        try {
            if(EmpytyFieldValidation())
            {
                Vehicle vehicle = new Vehicle(VehicleTxt.getText(),VehNumtxt.getText(),TypeVehtxt.getText(),Desctxt.getText());

                operatingSystem.addVehicle(vehicle);
                dB4OUtility.storeSystem(operatingSystem);

                MainJFrameForm suc = new MainJFrameForm();
                ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
                suc.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this,"Data Cant be empty. Please check over the red fields to know more.");
                emptyValidationStatus=true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Vehicle not registered, Try again");
            emptyValidationStatus=true;
        }
      
        
        
        
        /*
        try {
            if(EmpytyFieldValidation())
            {
                if(RegexValidation())
                {
                    String address = addresstxt.getText() + citytxt.getText() + state_txt.getText() + lblzip.getText();
                    //uname, pswd, id, name, add, gender, telenum, dob
                    //(txtFullName.getText(), txtNo.getText(), address, txtUsrName.getText(), txtPass.getText());

                    Technician tech = new Technician(usrnametxt.getText(), passtxt.getText(), "idid", fullname_txt.getText(), address, gender_cmb.getSelectedItem().toString(), telenum_txt.getText(), new Date(),labname_txt.getText());

                    operatingSystem.addTechnician(tech);
                    dB4OUtility.storeSystem(operatingSystem);

                    MainJFrameForm suc = new MainJFrameForm();
                    ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
                    suc.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Some Error in entered data.Please check over the red fields to know more.");
                    validationCheck=true;
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Data Cant be empty. Please check over the red fields to know more.");
                emptyValidationStatus=true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Patient not registered, Try again");
            emptyValidationStatus=true;
        }
        */

    }//GEN-LAST:event_SignUpbtnActionPerformed

    private boolean EmpytyFieldValidation() {
    if(VehicleTxt.getText().equals(null) || VehicleTxt.getText().trim().isEmpty() )
    {
        VehicleTxt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        VehicleTxt.setToolTipText("This Field Cannot be empty");
        emptyValidationStatus= false;
    }
    if(!VehicleTxt.getText().equals(null) && !VehicleTxt.getText().trim().isEmpty() )
    {
        VehicleTxt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    }

    if(VehNumtxt.getText().equals(null) || VehNumtxt.getText().trim().isEmpty() )
    {
        VehNumtxt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        VehNumtxt.setToolTipText("This Field Cannot be empty");
        emptyValidationStatus= false;
    }
    if(!VehNumtxt.getText().equals(null) && !VehNumtxt.getText().trim().isEmpty() )
    {
        VehNumtxt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    }

    if(TypeVehtxt.getText().equals(null) || TypeVehtxt.getText().trim().isEmpty() )
    {
        TypeVehtxt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        TypeVehtxt.setToolTipText("This Field Cannot be empty");
        emptyValidationStatus= false;
    }
    if(!TypeVehtxt.getText().equals(null) && !TypeVehtxt.getText().trim().isEmpty() )
    {
        TypeVehtxt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    }
    
    // if(addresstxt.getText().equals(null) || addresstxt.getText().trim().isEmpty() )
    //         {
    //             addresstxt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    //             addresstxt.setToolTipText("This Field Cannot be empty");
    //             emptyValidationStatus= false;
    //         }
    //         if(!addresstxt.getText().equals(null) && !addresstxt.getText().trim().isEmpty() )
    //         {
    //             addresstxt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    //         }

    //         if(citytxt.getText().equals(null) || citytxt.getText().trim().isEmpty() )
    //         {
    //             citytxt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    //             citytxt.setToolTipText("This Field Cannot be empty");
    //             emptyValidationStatus= false;
    //         }
    //         if(!citytxt.getText().equals(null) && !citytxt.getText().trim().isEmpty() )
    //         {
    //             citytxt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    //         }

    //         if(fullname_txt.getText().equals(null) || fullname_txt.getText().trim().isEmpty() )
    //         {
    //             fullname_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    //             fullname_txt.setToolTipText("This Field Cannot be empty");
    //             emptyValidationStatus= false;
    //         }
    //         if(!fullname_txt.getText().equals(null) && !fullname_txt.getText().trim().isEmpty() )
    //         {
    //             fullname_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    //         }

    //         if(passtxt.getText().equals(null) || passtxt.getText().trim().isEmpty() )
    //         {
    //             passtxt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    //             passtxt.setToolTipText("This Field Cannot be empty");
    //             emptyValidationStatus= false;
    //         }
    //         if(!passtxt.getText().equals(null) && !passtxt.getText().trim().isEmpty() )
    //         {
    //             passtxt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    //         }

    //         if(state_txt.getText().equals(null) || state_txt.getText().trim().isEmpty() )
    //         {
    //             state_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    //             state_txt.setToolTipText("This Field Cannot be empty");
    //             emptyValidationStatus= false;
    //         }
    //         if(!state_txt.getText().equals(null) && !state_txt.getText().trim().isEmpty() )
    //         {
    //             state_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    //         }

    //         if(usrnametxt.getText().equals(null) || usrnametxt.getText().trim().isEmpty() )
    //             {
    //                 usrnametxt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    //                 usrnametxt.setToolTipText("This Field Cannot be empty");
    //                 emptyValidationStatus= false;
    //             }
    //         if(!usrnametxt.getText().equals(null) && !usrnametxt.getText().trim().isEmpty() )
    //         {
    //             usrnametxt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    //         }

    //         if(lblzip.getText().equals(null) || lblzip.getText().trim().isEmpty() )
    //             {
    //                 lblzip.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    //                 lblzip.setToolTipText("This Field Cannot be empty");
    //                 emptyValidationStatus= false;
    //             }
    //         if(!lblzip.getText().equals(null) && !lblzip.getText().trim().isEmpty() )
    //         {
    //             lblzip.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    //         }

    //         if(labname_txt.getText().equals(null) || labname_txt.getText().trim().isEmpty() )
    //             {
    //                 labname_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    //                 labname_txt.setToolTipText("This Field Cannot be empty");
    //                 emptyValidationStatus= false;
    //             }
    //         if(!labname_txt.getText().equals(null) && !labname_txt.getText().trim().isEmpty() )
    //         {
    //             labname_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    //         }

    //         if(telenum_txt.getText().equals(null) || telenum_txt.getText().trim().isEmpty() )
    //             {
    //                 telenum_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    //                 telenum_txt.setToolTipText("This Field Cannot be empty");
    //                 emptyValidationStatus= false;
    //             }
    //         if(!telenum_txt.getText().equals(null) && !telenum_txt.getText().trim().isEmpty() )
    //         {
    //             telenum_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    //         }

    //         if(dob_txt.getText().equals(null) || dob_txt.getText().trim().isEmpty() )
    //             {
    //                 dob_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    //                 dob_txt.setToolTipText("This Field Cannot be empty");
    //                 emptyValidationStatus= false;
    //             }
    //         if(!dob_txt.getText().equals(null) && !dob_txt.getText().trim().isEmpty() )
    //         {
    //             dob_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    //         }

    if(Desctxt.getText().equals(null) || Desctxt.getText().trim().isEmpty() )
    {
        Desctxt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        Desctxt.setToolTipText("This Field Cannot be empty");
        emptyValidationStatus= false;
    }
    if(!Desctxt.getText().equals(null) && !Desctxt.getText().trim().isEmpty() )
    {
        Desctxt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
    }
    return emptyValidationStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_lbl;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel DescLbl;
    private javax.swing.JTextField Desctxt;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JButton SignUpbtn;
    private javax.swing.JTextField TypeVehtxt;
    private javax.swing.JLabel VehNumlbl;
    private javax.swing.JTextField VehNumtxt;
    private javax.swing.JTextField VehicleTxt;
    private javax.swing.JLabel admintitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
