/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SupplyChainInterface;

import javax.swing.JOptionPane;

import BackendDB4OUtility.DB4OUtility;
import OperatingSystems.OperatingSystem;
import BackendEnterpriseSupplyChain.Handler;
import BackendOrganization.DonationAssignment;
import LogisticsLoginPage.HandlerLogin;

import model.MainJFrameForm;

/**
 *
 * @author vidishaa
 */
public class LogisticsFrontPage extends javax.swing.JPanel {

    /**
     * Creates new form LogisticsFrontPage
     */
    MainJFrameForm MainLPage;
    private DB4OUtility dB4OUtility;
    private OperatingSystem operatingSystem;

    public LogisticsFrontPage(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();

        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logisticstitle = new javax.swing.JLabel();
        Rolelbl = new javax.swing.JLabel();
        cmb_role = new javax.swing.JComboBox<>();
        username_lbl = new javax.swing.JLabel();
        usrname_txt = new javax.swing.JTextField();
        pswd_lbl = new javax.swing.JLabel();
        passtxt = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        signinBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 1551));

        jPanel1.setMaximumSize(new java.awt.Dimension(1700, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(1700, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logisticstitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Logisticstitle.setText("Logistics");
        jPanel1.add(Logisticstitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        Rolelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Rolelbl.setText("Role:");
        jPanel1.add(Rolelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        cmb_role.setEditable(true);
        cmb_role.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Handler","Vehicle"}));
        cmb_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_roleActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 197, -1));

        username_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        username_lbl.setText("Username:");
        jPanel1.add(username_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        usrname_txt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel1.add(usrname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 197, -1));

        pswd_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pswd_lbl.setText("Password:");
        jPanel1.add(pswd_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        passtxt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel1.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 197, -1));

        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 86, 40));

        signinBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signinBtn.setText("Sign Up");
        signinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinBtnActionPerformed(evt);
            }
        });
        jPanel1.add(signinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/delivery-7022432.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(2999, 1999));
        jLabel2.setMinimumSize(new java.awt.Dimension(2999, 1999));
        jLabel2.setPreferredSize(new java.awt.Dimension(2999, 2000));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -420, 2720, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1712, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1700, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_roleActionPerformed
        // TODO add your handling code here:
        System.out.println(cmb_role.getSelectedItem().toString());
        if (cmb_role.getSelectedItem().toString() == "Admin") {
            signinBtn.setEnabled(false);
        } else {
            signinBtn.setEnabled(true);
        }
    }//GEN-LAST:event_cmb_roleActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:

        if (cmb_role.getSelectedItem().toString() == "Vehicle") {

            JOptionPane.showMessageDialog(this, "Vehicle not allow to login.");
        }

        //
        //        }
        if (cmb_role.getSelectedItem().toString() == "Handler") {
            Handler ho = (Handler) operatingSystem.loginAuthentication(usrname_txt.getText(), passtxt.getText());
            if (ho == null) {
                JOptionPane.showMessageDialog(this, "Incorrect credential");
            } else {
                HandlerLogin ap = new HandlerLogin(MainLPage, dB4OUtility, operatingSystem, ho);
                MainLPage.setContentPane(ap);
                MainLPage.invalidate();
                MainLPage.validate();
                return;
            }

        }
        //
        //        if (cmb_Role.getSelectedItem().toString() == "Patient") {
            //            DeliveryMan r = system.loginDeliveryMan(txtUsername.getText(), txtPassword.getText());
            //
            //            if (r == null) {
                //                JOptionPane.showMessageDialog(this, "Incorrect credential");
                //            } else {
                //                DeliverManMainPage delimp = new DeliverManMainPage(system, dB4OUtility, r);
                //                this.setContentPane(delimp);
                //                this.invalidate();
                //                this.validate();
                //                return;
                //            }
                //
                //        }

                //
                //            JOptionPane.showMessageDialog(this, "All fields are mandatory.");
                //        } else if (!name_chk.getText().equals("") || !telenum_chk.getText().equals("") || !add_chk.getText().equals("") || !city_chk.getText().equals("")
                //            || !state_chk.getText().equals("") || !zip_chk.getText().equals("")) {
                //
                //            JOptionPane.showMessageDialog(this, "Invalid value(s) entered.");
                //        }
                //        else{
                //            Address add = new Address(txtAdd.getText(), txtCity.getText(), txtState.getText(), Integer.parseInt(txtZip.getText()));
                //
                //            Customer cus =new Customer(txtUsrName.getText(), txtPass.getText(), new CustomerRole(),txtNo.getText(), txtFullName.getText(), add);
                //            system.addCustomer(cus);
                //
                //            dB4OUtility.storeSystem(system);
                //            JOptionPane.showMessageDialog(this, "Customer information saved.");
                //            MainJFrame cust = new MainJFrame();
                //            ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
                //            cust.setVisible(true);
                //
                //        if (cmb_Role.getSelectedItem().toString() == "Hospital Admin") {
                //            if (txtUsername.getText().matches("a") && txtPassword.getText().matches("a")) {
                //                AdminPage adminpg = new AdminPage(system, dB4OUtility);
                //                this.setContentPane(adminpg);
                //                this.invalidate();
                //                this.validate();
                //                return;
                //            } else {
                //                JOptionPane.showMessageDialog(this, "Incorrect credential");
                //            }
            //        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void signinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinBtnActionPerformed
        // TODO add your handling code here:

        if (cmb_role.getSelectedItem().toString() == "Vehicle") {

            VehicleSignUp signveh = new VehicleSignUp(MainLPage, dB4OUtility, operatingSystem);
            //
            //            //suc.setVisible(true);
            MainLPage.setContentPane(signveh);
            ////            //             this.add(s);
            ////
            MainLPage.invalidate();
            MainLPage.validate();

        }

        if (cmb_role.getSelectedItem().toString() == "Handler") {
            // System.out.println("Hospital");
            HandlerSignUp s = new HandlerSignUp(MainLPage, dB4OUtility, operatingSystem);

            //suc.setVisible(true);
            MainLPage.setContentPane(s);
            //             this.add(s);

            MainLPage.invalidate();
            MainLPage.validate();

        }
    }//GEN-LAST:event_signinBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logisticstitle;
    private javax.swing.JLabel Rolelbl;
    private javax.swing.JComboBox<String> cmb_role;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JLabel pswd_lbl;
    private javax.swing.JButton signinBtn;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JTextField usrname_txt;
    // End of variables declaration//GEN-END:variables
}
