/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdministrationInterface;

import javax.swing.table.DefaultTableModel;
import BackendDB4OUtility.DB4OUtility;
import OperatingSystems.OperatingSystem;
import BackendOrganization.DonationAssignment;

import model.MainJFrameForm;
import javax.swing.JOptionPane;


/**
 *
 * @author vidishaa
 */
public class ManageTransplants extends javax.swing.JPanel {

    /**
     * Creates new form ManageTransplants
     */
    MainJFrameForm MainLPage;
    //FirebaseHelper firebaseHelper;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;

    public ManageTransplants(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        UpdateStat_btn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Type", "Blood group", "Entity name", "Status", "Donor Enterprise", "Receiver Enterprise", "Patient Name", "Donar name", "Donor Doctor", "Receiver Doctor", "Handler Name", "Report", "Id"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        UpdateStat_btn.setBackground(new java.awt.Color(204, 0, 0));
        UpdateStat_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateStat_btn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateStat_btn.setText("Update Status");
        UpdateStat_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStat_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdateStat_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(UpdateStat_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateStat_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStat_btnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tb1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        String id = model.getValueAt(selectedRow, 12).toString();
        System.out.println(" handler uname: " + id);

        for(DonationAssignment de : operatingSystem.getDonationAssignmentList()){
            try{
                if(de.getId().equals(id)){
                    de.setDonationStatus(model.getValueAt(selectedRow, 3).toString());
                }
            }catch(Exception e){

            }
        }

        dB4OUtility.storeSystem(operatingSystem);
        JOptionPane.showMessageDialog(this, "Updated Status");

    }//GEN-LAST:event_UpdateStat_btnActionPerformed


    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        model.setRowCount(0);
        System.out.println("populatetable");
        for (DonationAssignment d : operatingSystem.getDonationAssignmentList()) {

            Object[] row = new Object[13];
            row[0] = d.getType();
            row[1] = d.getBloodgroup();
            row[2] = d.getDonationEntityName();
            row[3] = d.getDonationStatus();
            try {
                row[4] = d.getDonationenterprise().getEnterprisename();
            } catch (Exception e) {

            }

            try {
                row[5] = d.getRecordenterprise().getEnterprisename();
            } catch (Exception e) {

            }
            try {
                row[6] = d.getRecordpatient().getPersonName();
            } catch (Exception e) {

            }
            try {
                row[7] = d.getDonationpatient().getPersonName();
            } catch (Exception e) {

            }
            try {
            row[8] = d.getDonationdoc().getPersonName();
            }catch (Exception e) {

            }
            try {
            row[9] = d.getRecorddoc().getPersonName();
            }catch (Exception e) {

            }
            try{
            row[10] = d.getHandler().getPersonName();
            }catch (Exception e) {

            }
            try {
            row[11] = d.getDonationReport();
            }catch (Exception e) {

            }
            try {
            row[12] = d.getId();
            }catch (Exception e) {

            }

            model.addRow(row);

        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateStat_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
