/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdministrationInterface;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import BackendDB4OUtility.DB4;
import OperatingSystems.Operatesys;
import BackendEnterpriseDonorBank.DonorBank;
import BackendEnterpriseDonorBank.DonorUser;
import model.MainJFrameForm;

/**
 *
 * @author vidishaa
 */
public class ManageDonarBank extends javax.swing.JPanel {

    /**
     * Creates new form ManageDonarBank
     */
    MainJFrameForm MainLPage;
    //FirebaseHelper firebaseHelper;
    private Operatesys operatingSystem;
    private DB4 dB4OUtility;

    public ManageDonarBank(MainJFrameForm MainLPage, DB4 dB4OUtility, Operatesys operatingSystem) {
        initComponents();
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        populateDonorBankTable();
        populateDonorTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPanebBankdetails = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPaneDonarDetails = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        delbtn = new javax.swing.JButton();
        delbtn2 = new javax.swing.JButton();
        bankdetail_label = new javax.swing.JLabel();
        donardetail_label = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Registry Number", "Enterprise Name"
            }
        ));
        jScrollPanebBankdetails.setViewportView(table1);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Name", "Donor Bank Name"
            }
        ));
        jScrollPaneDonarDetails.setViewportView(table2);

        delbtn.setBackground(new java.awt.Color(204, 0, 51));
        delbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delbtn.setForeground(new java.awt.Color(255, 255, 255));
        delbtn.setText("Delete");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        delbtn2.setBackground(new java.awt.Color(204, 0, 51));
        delbtn2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delbtn2.setForeground(new java.awt.Color(255, 255, 255));
        delbtn2.setText("Delete");
        delbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtn2ActionPerformed(evt);
            }
        });

        bankdetail_label.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bankdetail_label.setText("Donor Bank Details");

        donardetail_label.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        donardetail_label.setText("Donor Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(bankdetail_label)
                .addContainerGap(718, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPanebBankdetails, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDonarDetails))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(475, 475, 475))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(472, 472, 472))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(donardetail_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(bankdetail_label)
                .addGap(18, 18, 18)
                .addComponent(jScrollPanebBankdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(donardetail_label)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneDonarDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(466, 466, 466))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1069, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = table1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        String doctorUName = model.getValueAt(selectedRow, 0).toString();
        System.out.println(" donorbank uname: " + doctorUName);
        operatingSystem.deleteDonorBank(doctorUName);
        dB4OUtility.storeSystem(operatingSystem);
        populateDonorBankTable();
        populateDonorTable();
    }//GEN-LAST:event_delbtnActionPerformed

    private void delbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtn2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = table2.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) table2.getModel();
        String doctorUName = model.getValueAt(selectedRow, 0).toString();
        System.out.println(" donor uname: " + doctorUName);
        operatingSystem.deleteDonor(doctorUName);
        dB4OUtility.storeSystem(operatingSystem);
        populateDonorBankTable();
        populateDonorTable();
    }//GEN-LAST:event_delbtn2ActionPerformed

    private void populateDonorTable() {
        DefaultTableModel model = (DefaultTableModel) table2.getModel();
        model.setRowCount(0);

        for (DonorUser d : operatingSystem.getDonorDirectory()) {

            Object[] row = new Object[5];
            row[0] = d.getUseName();
            row[1] = d.getPersoname();
            row[2]= d.getDonorBankName();
            model.addRow(row);

        }

    }
    
    private void populateDonorBankTable() {
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);

        for (DonorBank d : operatingSystem.getDonorBankDirectory()) {

            Object[] row = new Object[5];
            row[0] = d.getUsername();
            row[1] = d.getRegnum();
            row[2] = d.getEnterprisename();
            model.addRow(row);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankdetail_label;
    private javax.swing.JButton delbtn;
    private javax.swing.JButton delbtn2;
    private javax.swing.JLabel donardetail_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneDonarDetails;
    private javax.swing.JScrollPane jScrollPanebBankdetails;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
