/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdministrationInterface;

import BackendDB4OUtility.DB4OUtility;
import OperatingSystems.OperatingSystem;
import model.MainJFrameForm;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;


/**
 *
 * @author vidishaa
 */
public class AdminSplitPage extends javax.swing.JPanel {

    /**
     * Creates new form AdminSplitPage
     */
    MainJFrameForm MainLPage;
    //FirebaseHelper firebaseHelper;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;

    public AdminSplitPage(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        DonarbankBtn = new javax.swing.JButton();
        hospBtn = new javax.swing.JButton();
        transbtn = new javax.swing.JButton();
        Logoutbtn = new javax.swing.JButton();
        LogBtn = new javax.swing.JButton();
        graphsbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        DonarbankBtn.setBackground(new java.awt.Color(0, 0, 102));
        DonarbankBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DonarbankBtn.setForeground(new java.awt.Color(255, 255, 255));
        DonarbankBtn.setText("Manage Donor Bank");
        DonarbankBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonarbankBtnActionPerformed(evt);
            }
        });

        hospBtn.setBackground(new java.awt.Color(0, 0, 102));
        hospBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hospBtn.setForeground(new java.awt.Color(255, 255, 255));
        hospBtn.setText("Manage Hospital");
        hospBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospBtnActionPerformed(evt);
            }
        });

        transbtn.setBackground(new java.awt.Color(0, 0, 102));
        transbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        transbtn.setForeground(new java.awt.Color(255, 255, 255));
        transbtn.setText("Manage Transplants");
        transbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transbtnActionPerformed(evt);
            }
        });

        Logoutbtn.setBackground(new java.awt.Color(255, 204, 204));
        Logoutbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Logoutbtn.setText("Logout");
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        LogBtn.setBackground(new java.awt.Color(0, 0, 102));
        LogBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LogBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogBtn.setText("Manage Logistics");
        LogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtnActionPerformed(evt);
            }
        });

        graphsbtn.setBackground(new java.awt.Color(0, 0, 102));
        graphsbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        graphsbtn.setForeground(new java.awt.Color(255, 255, 255));
        graphsbtn.setText("Graphs");
        graphsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphsbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DonarbankBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graphsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hospBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(hospBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(DonarbankBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(LogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(graphsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(transbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DonarbankBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonarbankBtnActionPerformed
        // TODO add your handling code here:
        ManageDonarBank mdb = new ManageDonarBank(MainLPage, dB4OUtility, operatingSystem);
        jSplitPane1.setRightComponent(mdb);
    }//GEN-LAST:event_DonarbankBtnActionPerformed

    private void hospBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospBtnActionPerformed
        // TODO add your handling code here:
        ManageHospital ap = new ManageHospital(MainLPage, dB4OUtility, operatingSystem);
        jSplitPane1.setRightComponent(ap);
    }//GEN-LAST:event_hospBtnActionPerformed

    private void transbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transbtnActionPerformed
        // TODO add your handling code here:
        ManageTransplants mt = new ManageTransplants(MainLPage, dB4OUtility, operatingSystem);
        jSplitPane1.setRightComponent(mt);
    }//GEN-LAST:event_transbtnActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // TODO add your handling code here:
        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void LogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtnActionPerformed
        // TODO add your handling code here:

        ManageLogistics mdb = new ManageLogistics(MainLPage, dB4OUtility, operatingSystem);
        jSplitPane1.setRightComponent(mdb);
    }//GEN-LAST:event_LogBtnActionPerformed

    private void graphsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphsbtnActionPerformed
        // TODO add your handling code here:
        //        ManageTransplant mt = new ManageTransplant(MainLPage, dB4OUtil, ecoSystem);
        Visualization mt = new Visualization(MainLPage, dB4OUtility, operatingSystem);
        jSplitPane1.setRightComponent(mt);
    }//GEN-LAST:event_graphsbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DonarbankBtn;
    private javax.swing.JButton LogBtn;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JButton graphsbtn;
    private javax.swing.JButton hospBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton transbtn;
    // End of variables declaration//GEN-END:variables
}
