/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DonarBankProfileLogin;
import BackendDB4OUtility.DB4OUtility;
import BackendEnterpriseDonorBank.DonorUser;
import OperatingSystems.OperatingSystem;
import model.MainJFrameForm;
import java.awt.Color;
import javax.swing.BorderFactory;
/**
 *
 * @author vidishaa
 */
  


public class ProfileDetailsDonor extends javax.swing.JPanel {

    /**
     * Creates new form ProfileDetailsDonor
     */
    
    boolean emptyValidationStatus = true;
    boolean validationCheck = true;
    
    MainJFrameForm MainLPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    DonorUser don;
    
    public ProfileDetailsDonor(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem, DonorUser don) {
        initComponents();
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        this.don = don;
        
        
        txtName.setText(don.getPersonName());
        txtUName.setText(don.getUserName());
        txtAddHosp.setText(don.getAddress());
        txtTeleName.setText(don.getPhoneNumber());
        txtDOB.setText(don.getDateOfBirth().toString());
        txtDonor.setText(don.getDonorbankname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblUName = new javax.swing.JLabel();
        txtUName = new javax.swing.JTextField();
        lblAddHosp = new javax.swing.JLabel();
        txtAddHosp = new javax.swing.JTextField();
        lblTeleName = new javax.swing.JLabel();
        txtTeleName = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblDonarbnkname = new javax.swing.JLabel();
        txtDonor = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));

        lbltitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbltitle.setText("Donor Details");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Name:");

        txtName.setEditable(false);

        lblUName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUName.setText("Username:");

        txtUName.setEditable(false);

        lblAddHosp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddHosp.setText("Address:");

        txtAddHosp.setEditable(false);

        lblTeleName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTeleName.setText("Phone no.:");

        txtTeleName.setEditable(false);
        txtTeleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleNameActionPerformed(evt);
            }
        });
        txtTeleName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTeleNameKeyReleased(evt);
            }
        });

        lblDOB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDOB.setText("Date of Birth:");

        txtDOB.setEditable(false);
        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });
        txtDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDOBKeyReleased(evt);
            }
        });

        lblDonarbnkname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDonarbnkname.setText("Donor Bank:");

        txtDonor.setEditable(false);
        txtDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonorActionPerformed(evt);
            }
        });
        txtDonor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDonorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddHosp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDOB)
                                .addComponent(lblDonarbnkname, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTeleName)
                            .addGap(30, 30, 30)
                            .addComponent(txtTeleName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltitle)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lbltitle)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUName))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddHosp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeleName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDonarbnkname)
                    .addComponent(txtDonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleNameActionPerformed

    private void txtTeleNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleNameKeyReleased

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtDOBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBKeyReleased

    private void txtDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonorActionPerformed

    private void txtDonorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDonorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonorKeyReleased

    private boolean RegexValidation() {
    if(!txtName.getText().matches("^[a-zA-Z ]+$"))
        {
            txtName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtName.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(!txtTeleName.getText().matches("^[0-9]{10}$"))
        {
            txtTeleName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtTeleName.setToolTipText("Please enter a 10 digit number");
            validationCheck=false;
        }


        // if(!txtZip.getText().matches("^[0-9]{5}$"))
        // {
        //     txtZip.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        //     txtZip.setToolTipText("Please enter a 5 digit number");
        //     validationCheck=false;
        // }

        // if(!txt_spc.getText().matches("^[0-9]{5}$"))
        // {
        //     txt_spc.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        //     txt_spc.setToolTipText("Please enter a 5 digit number");
        //     validationCheck=false;
        // }

        return validationCheck;


    }   


    private boolean EmpytyFieldValidation() {

        if(txtName.getText().equals(null) || txtName.getText().trim().isEmpty() )
        {
            txtName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtName.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtName.getText().equals(null) && !txtName.getText().trim().isEmpty() )
        {
            txtName.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txtUName.getText().equals(null) || txtUName.getText().trim().isEmpty() )
            {
                txtUName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                txtUName.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!txtUName.getText().equals(null) && !txtUName.getText().trim().isEmpty() )
        {
            txtUName.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txtAddHosp.getText().equals(null) || txtAddHosp.getText().trim().isEmpty() )
        {
            txtAddHosp.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtAddHosp.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtAddHosp.getText().equals(null) && !txtAddHosp.getText().trim().isEmpty() )
        {
            txtAddHosp.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txtTeleName.getText().equals(null) || txtTeleName.getText().trim().isEmpty() )
        {
            txtTeleName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtTeleName.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtTeleName.getText().equals(null) && !txtTeleName.getText().trim().isEmpty() )
        {
            txtTeleName.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        
        if(txtDOB.getText().equals(null) || txtDOB.getText().trim().isEmpty() )
        {
            txtDOB.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtDOB.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtDOB.getText().equals(null) && !txtDOB.getText().trim().isEmpty() )
        {
            txtDOB.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txtDonor.getText().equals(null) || txtDonor.getText().trim().isEmpty() )
        {
            txtDonor.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtDonor.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtDonor.getText().equals(null) && !txtDonor.getText().trim().isEmpty() )
        {
            txtDonor.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        // if(txtZip.getText().equals(null) || txtZip.getText().trim().isEmpty() )
        //     {
        //         txtZip.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        //         txtZip.setToolTipText("This Field Cannot be empty");
        //         emptyValidationStatus= false;
        //     }
        // if(!txtZip.getText().equals(null) && !txtZip.getText().trim().isEmpty() )
        // {
        //     txtZip.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        // }

        // if(txt_spc.getText().equals(null) || txt_spc.getText().trim().isEmpty() )
        //     {
        //         txt_spc.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        //         txt_spc.setToolTipText("This Field Cannot be empty");
        //         emptyValidationStatus= false;
        //     }
        // if(!txt_spc.getText().equals(null) && !txt_spc.getText().trim().isEmpty() )
        // {
        //     txt_spc.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        // }

        // if(txtTeleName.getText().equals(null) || txtTeleName.getText().trim().isEmpty() )
        //     {
        //         txtTeleName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        //         txtTeleName.setToolTipText("This Field Cannot be empty");
        //         emptyValidationStatus= false;
        //     }
        // if(!txtTeleName.getText().equals(null) && !txtTeleName.getText().trim().isEmpty() )
        // {
        //     txtTeleName.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        // }
        
        return emptyValidationStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddHosp;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDonarbnkname;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTeleName;
    private javax.swing.JLabel lblUName;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField txtAddHosp;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDonor;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTeleName;
    private javax.swing.JTextField txtUName;
    // End of variables declaration//GEN-END:variables
}
