/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DonarAdminBankLogin;

import BackendDB4OUtility.DB4;
import OperatingSystems.Operatesys;
import BackendEnterpriseDonorBank.DonorBank;
import BackendOrganization.DonationAssignment;
import model.MainJFrameForm;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vidishaa
 */
public class DonarAdminTransplant extends javax.swing.JPanel {

    /**
     * Creates new form DonarAdminTransplant
     */
    MainJFrameForm MainLPage;
    private Operatesys operatingSystem;
    private DB4 dB4OUtility;
    DonorBank donorBank;
    
    public DonarAdminTransplant(MainJFrameForm MainLPage, DB4 dB4OUtility, Operatesys operatingSystem, DonorBank donbank) {
        initComponents();
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        this.donorBank = donbank;
        populateTable(donbank.getEnterprisename().toLowerCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 102));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Types", "Blood Group", "Entity name", "Status", "Donor list", "Receiver list", "Patient's Name", "Donar's name"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1041, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(185, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    
     private void populateTable(String name) {
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        model.setRowCount(0);
        System.out.println("populatetable");
        for (DonationAssignment d : operatingSystem.getDonationAssignList()) {

            if (d.getDonationenterprise().getEnterprisename().toLowerCase().equals(name)) {
                Object[] row = new Object[8];
                row[0] = d.getType();
                row[1] = d.getBloodgroup();
                row[2] = d.getDonationEntityName();
                row[3] = d.getDonationStatus();
                try {
                    row[4] = d.getDonationenterprise().getEnterprisename();
                } catch (Exception e) {

                }

                try {
                    row[5] = d.getRecordenterprise().getEnterprisename();
                } catch (Exception e) {

                }
                try {
                    row[6] = d.getRecordpatient().getUseName();
                } catch (Exception e) {

                }
                try {
                    row[7] = d.getDonationpatient().getUseName();
                } catch (Exception e) {

                }

                model.addRow(row);
            }
            try {
                if (d.getRecordenterprise().getEnterprisename().toLowerCase().equals(name)) {
                    Object[] row = new Object[8];
                    row[0] = d.getType();
                    row[1] = d.getBloodgroup();
                    row[2] = d.getDonationEntityName();
                    row[3] = d.getDonationStatus();
                    try {
                        row[4] = d.getDonationenterprise().getEnterprisename();
                    } catch (Exception e) {

                    }

                    try {
                        row[5] = d.getRecordenterprise().getEnterprisename();
                    } catch (Exception e) {

                    }
                    try {
                        row[6] = d.getRecordpatient().getUseName();
                    } catch (Exception e) {

                    }
                    try {
                        row[7] = d.getDonationpatient().getUseName();
                    } catch (Exception e) {

                    }

                    model.addRow(row);
                }
            } catch (Exception e) {

            }

        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
