/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DonarAdminBankLogin;

import BackendDB4OUtility.DB4;
import OperatingSystems.Operatesys;
import BackendEnterpriseDonorBank.DonorUser;
import BackendEnterpriseDonorBank.DonorBank;
import BackendOrganization.DonationAssignment;
import model.MainJFrameForm;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author vidishaa
 */
public class DonarAdminOrganDonate extends javax.swing.JPanel {

    /**
     * Creates new form DonarAdminOrganDonate
     */
    
    MainJFrameForm MainLPage;
    private Operatesys operatingSystem;
    private DB4 dB4OUtility;
    DonorBank donorBank;
    
    public DonarAdminOrganDonate(MainJFrameForm MainLPage, DB4 dB4OUtility, Operatesys operatingSystem, DonorBank donarbank) {
        initComponents();
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        this.donorBank = donarbank;
        
        for(DonorUser pa : operatingSystem.getDonorDirectory() ){
            System.out.println("DonorAdminDonateOrgan"+pa.getDonorBankName());
            if( pa.getDonorBankName().equals(donarbank.getEnterprisename())){
                listdon.addItem(pa.getUseName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlelbl = new javax.swing.JLabel();
        donornamelbl = new javax.swing.JLabel();
        enttypelbl = new javax.swing.JLabel();
        entnametxt = new javax.swing.JTextField();
        enttypecmb = new javax.swing.JComboBox<>();
        entnamelbl = new javax.swing.JLabel();
        bldgrplbl = new javax.swing.JLabel();
        bldgrptxt = new javax.swing.JTextField();
        statuslbl = new javax.swing.JLabel();
        statuscmb = new javax.swing.JComboBox<>();
        savebtn = new javax.swing.JButton();
        listdon = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 102, 102));

        titlelbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titlelbl.setText("Add Entity Details");

        donornamelbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        donornamelbl.setText("Donor Name:");

        enttypelbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enttypelbl.setText("Entity Type:");

        enttypecmb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enttypecmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blood", "Organ" }));

        entnamelbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        entnamelbl.setText("Entity Name:");

        bldgrplbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bldgrplbl.setText("Blood Group:");

        statuslbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        statuslbl.setText("Status:");

        statuscmb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        statuscmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));

        savebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        listdon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(bldgrplbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bldgrptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titlelbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(donornamelbl)
                                    .addComponent(enttypelbl)
                                    .addComponent(entnamelbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(entnametxt)
                                    .addComponent(enttypecmb, 0, 156, Short.MAX_VALUE)
                                    .addComponent(listdon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statuslbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savebtn)
                            .addComponent(statuscmb, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(titlelbl)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(donornamelbl)
                    .addComponent(listdon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enttypelbl)
                    .addComponent(enttypecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entnamelbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldgrptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bldgrplbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statuslbl)
                    .addComponent(statuscmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(savebtn)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:

        DonationAssignment de = new DonationAssignment();
        de.setDonationEntityName(entnametxt.getText().toString());
        de.setDonationenterprise(donorBank);
        Random rand = new Random();
        de.setId( String.format("%04d", rand.nextInt(10000)));
        de.setBloodgroup(bldgrptxt.getText().toString());
        de.setType(enttypecmb.getSelectedItem().toString());
        //de.setDonorDoctor(ecoSystem.findDoctorByUserName(doctorList.getSelectedItem().toString()));
        de.setDonationpatient(operatingSystem.getPatientByUserName(listdon.getSelectedItem().toString()));
        de.setDonationStatus(statuscmb.getSelectedItem().toString());
        //        System.out.println("dede: "+de.getDonorDoctor().getName());
        operatingSystem.addDonationAssignment(de);

        dB4OUtility.storeSystem(operatingSystem);

        JOptionPane.showMessageDialog(this, "Entity details added.");
    }//GEN-LAST:event_savebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bldgrplbl;
    private javax.swing.JTextField bldgrptxt;
    private javax.swing.JLabel donornamelbl;
    private javax.swing.JLabel entnamelbl;
    private javax.swing.JTextField entnametxt;
    private javax.swing.JComboBox<String> enttypecmb;
    private javax.swing.JLabel enttypelbl;
    private javax.swing.JComboBox<String> listdon;
    private javax.swing.JButton savebtn;
    private javax.swing.JComboBox<String> statuscmb;
    private javax.swing.JLabel statuslbl;
    private javax.swing.JLabel titlelbl;
    // End of variables declaration//GEN-END:variables
}
